# Generated by Django 4.1.3 on 2022-12-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='dayAsInt',
            field=models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], default=1),
        ),
    ]
