# Generated by Django 4.1.3 on 2022-11-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtf.region')),
            ],
        ),
    ]
