# Generated by Django 4.1.3 on 2022-11-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtf', '0002_ig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('ig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtf.ig')),
            ],
        ),
    ]
