# Generated by Django 4.1.3 on 2022-12-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtf', '0002_meeting_dayasint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='day',
        ),
    ]
