# Generated by Django 4.1.3 on 2022-11-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtf', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250)),
                ('postcode', models.CharField(max_length=10)),
                ('lattitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('disabledAccess', models.BooleanField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
