# Generated by Django 4.1.3 on 2022-12-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtf', '0004_rename_dayasint_meeting_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='longtitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
