# Generated by Django 4.1.3 on 2022-11-15 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtf', '0004_venue_alter_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='lattitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('startTime', models.TimeField()),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtf.group')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtf.venue')),
            ],
        ),
    ]
