# Generated by Django 4.1.3 on 2022-11-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtf', '0006_venue_address3_alter_meeting_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='longitude',
            new_name='longtitude',
        ),
    ]
