# Generated by Django 4.1.3 on 2022-11-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtf', '0007_rename_lattitude_venue_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='longtitude',
            field=models.FloatField(null=True),
        ),
    ]
