# Generated by Django 4.1.3 on 2022-11-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtf', '0010_town_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
