# Generated by Django 4.1.3 on 2022-11-30 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtf', '0011_town_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='town',
            field=models.ForeignKey(blank=True, default='Cambridge', on_delete=django.db.models.deletion.PROTECT, to='wtf.town'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
