# Generated by Django 4.1.3 on 2022-11-30 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtf', '0013_alter_venue_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='town',
            field=models.ForeignKey(blank=True, default=53, on_delete=django.db.models.deletion.PROTECT, to='wtf.town'),
        ),
    ]
